// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rgpxwptyoopfhkcvmnpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJncHh3cHR5b29wZmhrY3ZtbnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjEyNjcsImV4cCI6MjA3MzkzNzI2N30.yLBiKRqG6ZLb96ClI6Ogs5g-pXzyKDMVTLtbkEOdNLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);